baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Denis Mwangangi"

disableKinds = ["taxonomy", "term"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
