baseURL = "https://denismwangangi.com/"
languageCode = "en"
title = "Denis Mwangangi | Digita Garden"
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[permalinks]
  fiction     = "/:year/:month/:day/:slug/"
  non-fiction = "/:year/:month/:day/:slug/"
  adr         = "/:year/:month/:day/:slug/"

[taxonomies]
  category = "categories"   # non-fiction only
  type     = "types"        # fiction only
  status   = "status"       # note / draft / complete / archived
